/*
 * This file is generated by jOOQ.
 */
package com.leon.quick.tables.pojos;


import java.io.Serializable;
import java.math.BigInteger;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CodeCommit implements Serializable {

    private static final long serialVersionUID = -1248964403;

    private String     username;
    private BigInteger totalCommitNum;
    private BigInteger addedFileNum;
    private BigInteger addedLineNum;
    private byte[]     totalCommitNumSeries;

    public CodeCommit() {}

    public CodeCommit(CodeCommit value) {
        this.username = value.username;
        this.totalCommitNum = value.totalCommitNum;
        this.addedFileNum = value.addedFileNum;
        this.addedLineNum = value.addedLineNum;
        this.totalCommitNumSeries = value.totalCommitNumSeries;
    }

    public CodeCommit(
        String     username,
        BigInteger totalCommitNum,
        BigInteger addedFileNum,
        BigInteger addedLineNum,
        byte[]     totalCommitNumSeries
    ) {
        this.username = username;
        this.totalCommitNum = totalCommitNum;
        this.addedFileNum = addedFileNum;
        this.addedLineNum = addedLineNum;
        this.totalCommitNumSeries = totalCommitNumSeries;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public BigInteger getTotalCommitNum() {
        return this.totalCommitNum;
    }

    public void setTotalCommitNum(BigInteger totalCommitNum) {
        this.totalCommitNum = totalCommitNum;
    }

    public BigInteger getAddedFileNum() {
        return this.addedFileNum;
    }

    public void setAddedFileNum(BigInteger addedFileNum) {
        this.addedFileNum = addedFileNum;
    }

    public BigInteger getAddedLineNum() {
        return this.addedLineNum;
    }

    public void setAddedLineNum(BigInteger addedLineNum) {
        this.addedLineNum = addedLineNum;
    }

    public byte[] getTotalCommitNumSeries() {
        return this.totalCommitNumSeries;
    }

    public void setTotalCommitNumSeries(byte... totalCommitNumSeries) {
        this.totalCommitNumSeries = totalCommitNumSeries;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CodeCommit (");

        sb.append(username);
        sb.append(", ").append(totalCommitNum);
        sb.append(", ").append(addedFileNum);
        sb.append(", ").append(addedLineNum);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
