/*
 * This file is generated by jOOQ.
 */
package com.leon.quick;


import com.leon.quick.tables.CodeCommit;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in analyze_source
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>analyze_source.code_commit</code>.
     */
    public static final CodeCommit CODE_COMMIT = com.leon.quick.tables.CodeCommit.CODE_COMMIT;
}
